### ISSUE TITLE
Does not work in Xcode 7.3

### ISSUE THREAD

**Issue by deniskirillov** [tinymind/LSLog-XCode#6]
It does not work in Xcode 7.3 :(

**Comment by chlinxxoo** [comment]
me too

**Comment by tinymind** [comment]
Please check it out again, supports XCode 7.3 now.

**Comment by chlinxxoo** [comment]
Does it works in Alcatraz?I try to reinstall in Alcatraz, but it doesn't work after restart xcode.

**Comment by tinymind** [comment]
Sorry I thought it should be auto updated by Alcatraz. If it does not, please build and run in XCode. I will update it to Alcatraz later.

**Comment by deniskirillov** [comment]
Doesn't work after "build and run" in XCode. Only displaying as installed in Alcatraz, but no effect....

**Comment by ruixingchen** [comment]
just not work neither, nothing happened  after installed from Alcatraz and restart Xcode, biubiubiu~~~

**Comment by jstuth** [comment]
Looks like this problem is related to this XCode error message:
"[LSLog:addFilterViews] DVTScopeBarView not found"

**Comment by jstuth** [comment]
and perhaps that one:
"Failed to connect (borderedView) outlet from (IDELogAndTestsEditor) to (DVTBorderedView): missing setter or instance variable"

EDIT: sorry i'm wrong, this is an error, that also appears, when the LSLog Plugin is not installed. So ignore it ;)

**Comment by radsimu** [comment]
Still not working in 7.3... no settings button, no filterring box... nothing

**Comment by MrLu** [comment]
replace this line of code"NSView *consoleParentView = [self getParantViewByClassName:@"DVTControllerContentView" ofView:consoleTextView];" to "consoleParentView = [self getParantViewByClassName:@"DVTControllerContentView_ControlledBy_IDEConsoleArea" ofView:consoleTextView];" can resole the ploblem "It does not work in Xcode 7.3"

**Comment by tinymind** [comment]
Thanks @MrLu .
