### ISSUE TITLE
Settings button is missing 

### ISSUE THREAD

**Issue by ildar-gilfanov** [tinymind/LSLog-XCode#7]
I use 10.11.4 OSX and XCode 7.3. There is no settings button in debug area. Also I have tried to launch this project via XCode and get errors in log:

```
2016-04-21 09:48:02.147 Xcode[11800:356489] [LSLog:addFilterViews] DVTScopeBarView not found
2016-04-21 09:48:02.148 Xcode[11800:356489] [LSLog:addFilterViews] DVTScopeBarView not found
2016-04-21 09:48:02.784 Xcode[11800:356489] [LSLog:addFilterViews] DVTScopeBarView not found
...
```

![1](https://cloud.githubusercontent.com/assets/11190564/14700228/fd574bd0-07ae-11e6-8b6d-3c455921c695.png)

**Comment by deniskirillov** [comment]
I have the same problem...

**Comment by reddemonnet** [comment]
Same problem

**Comment by romaintaillandier1978** [comment]
Same problem

**Comment by tinymind** [comment]
Please update or re-install via Alcatraz, thanks.

**Comment by romaintaillandier1978** [comment]
Hello Tinymind,

The alcatraz pluggin can't be installed for me. Xcode 7.3.1. I can't know why. the install progress bar stop immediatly. Anyway it does not matter, i downloaded sources, and run it, and it's works fine.

I was missing your plugin. I can't do without it.
Thank you for the update. Great job

By the way, LSLog, and KZLinkedLog make the combo !
Romain TAILLANDIER
