### ISSUE TITLE
coloring doesn't work correctly

### ISSUE THREAD

**Issue by p0fi** [tinymind/LSLog-XCode#8]
Hi,
the coloring of the log output doesn't work correctly. Sometimes colors start in the middle of a logging statement and somethings entire lines are in the wrong color :( 

![2016-04-25 at 15 23](https://cloud.githubusercontent.com/assets/6141293/14785197/e84b7236-0af9-11e6-9bd6-af8b00e54a8d.png)

the lines marked in red are either completely wrong colored (should be black) or half way wrong colored.
Any way to solve this?

**Comment by tinymind** [comment]
Thanks for your feedback, I'm looking into this.

**Comment by p0fi** [comment]
Any updates here? :)
